# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MrvTeraka
                                 A QGIS plugin
 plugin for the mrv team in iTeraka
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-19
        copyright            : (C) 2026 by iTeraka
        email                : rosajohar@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


try:
    from .synthetic_data_generator import create_synthetic_project_data
except Exception:  # pragma: no cover - allow import outside QGIS
    def create_synthetic_project_data():
        raise RuntimeError(
            "create_synthetic_project_data is unavailable: import and run this inside QGIS where qgis.core is available or import mrv_teraka.synthetic_data_generator directly."
        )

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MrvTeraka class from file MrvTeraka.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mrv_teraka import MrvTeraka
    return MrvTeraka(iface)

__all__ = ['classFactory', 'create_synthetic_project_data']
