# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MrvTerakaDockWidget
                                 A QGIS plugin
 plugin for the mrv team in iTeraka
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-19
        git sha              : $Format:%H$
        copyright            : (C) 2026 by iTeraka
        email                : rosajohar@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal, Qt
from qgis.PyQt.QtWidgets import (
    QHBoxLayout, QVBoxLayout, QLabel, QPushButton, QWidget, QGroupBox, QSpacerItem, QSizePolicy
)
from qgis.PyQt.QtGui import QColor, QIcon

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'mrv_teraka_dockwidget_base.ui'))


class MrvTerakaDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()
    auth_requested = pyqtSignal()
    logout_requested = pyqtSignal()

    def __init__(self, plugin=None, parent=None):
        """Constructor."""
        super(MrvTerakaDockWidget, self).__init__(parent)
        self.plugin = plugin
        self.setupUi(self)
        self.setup_auth_ui()
        self.setup_connections()

    def setup_auth_ui(self):
        """Initialise les composants UI et les info-bulles."""
        # Les widgets sont maintenant définis dans le fichier .ui
        # On mappe les noms d'objets XML aux membres Python attendus
        self.status_label = self.statusLabel
        self.user_label = self.userLabel
        self.logout_button = self.logoutButton

        # Mapping des nouveaux ComboBox
        self.endpointLineEdit = self.endpointComboBox.lineEdit()

        # Remplir les listes déroulantes depuis le mapping
        self.populate_table_lists()
        self.populate_project_list()

        # Configuration des icônes et info-bulles (ergonomie)
        self.logout_button.setIcon(QIcon(':/plugins/mrv_teraka/login_icon.svg'))
        self.logout_button.setToolTip("Se déconnecter de l'API et effacer le jeton local")

        self.districtLineEdit.setPlaceholderText("Filtrer par district (ex: Mandoto)")

        self.compareButton.setToolTip("Comparer le nombre d'enregistrements entre QGIS et la base de données")
        self.loadDbButton.setToolTip("Charger les données de la table sélectionnée directement dans QGIS")
        self.processProjectButton.setToolTip("Analyser le projet pour décider d'une migration initiale ou d'un workflow terrain")

        self.autoPrepareButton.setToolTip("Déployer la mission sur Mergin Maps Cloud (Création projet + Upload GPKG)")
        self.autoImportButton.setToolTip("Récupérer les données depuis le terrain (Download depuis Mergin Cloud)")
        self.autoValidateButton.setToolTip("Valider les données via le moteur de règles métier iTeraka")
        self.autoSyncButton.setToolTip("Intégrer définitivement les données validées en base de données")
        self.refreshFromApiButton.setToolTip("Recharger les données depuis l'API PostgREST")

    def populate_table_lists(self):
        """Remplit les ComboBox avec les tables disponibles dans le mapping."""
        if not self.plugin:
            return

        mappings = self.plugin.load_layer_mappings()
        tables = sorted(list(mappings.keys()))

        self.endpointComboBox.clear()
        self.endpointComboBox.addItems(tables)


    def populate_project_list(self):
        """Remplit la liste des projets existants."""
        if not self.plugin or not self.plugin.mergin_manager:
            return

        self.projectComboBox.clear()
        projects = self.plugin.mergin_manager.list_projects()
        for p in projects:
            self.projectComboBox.addItem(p.get('name', 'Sans nom'), p.get('id'))

    def setup_connections(self):
        """Connecte les signaux aux slots du plugin."""
        if not self.plugin:
            return

        # Connexions garanties par le fichier .ui
        self.loadProjectButton.clicked.connect(self.on_load_project_clicked)
        self.saveProjectButton.clicked.connect(self.plugin.save_current_project_configuration)

        self.compareButton.clicked.connect(self.plugin.compare_project_with_db)
        self.loadDbButton.clicked.connect(self.plugin.load_database_data)
        self.processProjectButton.clicked.connect(self.plugin.analyze_and_process_project)

        self.autoPrepareButton.clicked.connect(self.plugin.auto_deploy_mission)
        self.autoImportButton.clicked.connect(self.plugin.auto_import_mission)
        self.autoValidateButton.clicked.connect(self.plugin.auto_validate_mission)
        self.autoSyncButton.clicked.connect(self.plugin.auto_finalize_mission)
        self.refreshFromApiButton.clicked.connect(self.plugin.refresh_data_via_api)

        # Bouton de déconnexion
        self.logout_button.clicked.connect(self.on_logout_clicked)

    def on_logout_clicked(self):
        """Gère le clic sur le bouton de déconnexion"""
        self.logout_requested.emit()

    def on_load_project_clicked(self):
        """Gère le chargement d'un projet sélectionné."""
        project_id = self.projectComboBox.currentData()
        if not project_id:
            # Essayer de trouver par nom si pas de data (cas editable)
            name = self.projectComboBox.currentText()
            projects = self.plugin.mergin_manager.list_projects()
            for p in projects:
                if p.get('name') == name:
                    project_id = p.get('id')
                    break

        if project_id:
            self.plugin.load_project_by_id(project_id)
        else:
            QtWidgets.QMessageBox.warning(self, "Projet introuvable", "Veuillez sélectionner un projet valide.")

    def set_status_message(self, message, color="black"):
        """Met à jour uniquement le message de statut."""
        self.status_label.setText(message)
        self.status_label.setStyleSheet(f"color: {color}; font-weight: bold;")

    def set_authenticated(self, username=None, api_url=None):
        """Affiche l'état connecté et active les contrôles."""
        self.status_label.setText("● Connecté")
        self.status_label.setStyleSheet("color: green; font-weight: bold;")

        if username and api_url:
            self.user_label.setText(f"{username} @ {api_url}")

        self.logout_button.setEnabled(True)

        # Recharger les tables dynamiquement si possible
        self.populate_table_lists()
        self.populate_project_list()

        # Activer les groupes et les listes
        self.groupBoxProject.setEnabled(True)
        self.groupBoxDB.setEnabled(True)
        self.groupBoxMergin.setEnabled(True)
        self.endpointComboBox.setEnabled(True)

        # Activer les boutons d'action de base
        self.compareButton.setEnabled(True)
        self.loadDbButton.setEnabled(True)
        self.processProjectButton.setEnabled(True)

        # Mission UI
        self.autoPrepareButton.setEnabled(True)
        self.autoImportButton.setEnabled(True)
        self.autoValidateButton.setEnabled(True)
        self.autoSyncButton.setEnabled(True)
        self.refreshFromApiButton.setEnabled(True)

    def set_unauthenticated(self):
        """Affiche l'état déconnecté et désactive les contrôles."""
        self.status_label.setText("● Déconnecté")
        self.status_label.setStyleSheet("color: red; font-weight: bold;")
        self.user_label.setText("Pas connecté")
        self.logout_button.setEnabled(False)

        # Désactiver les groupes et les listes
        self.groupBoxProject.setEnabled(False)
        self.groupBoxDB.setEnabled(False)
        self.groupBoxMergin.setEnabled(False)
        self.endpointComboBox.setEnabled(False)

        # Désactiver tous les boutons d'action
        buttons = [
            'compareButton', 'loadDbButton', 'processProjectButton',
            'autoPrepareButton', 'autoImportButton', 'autoValidateButton',
            'autoSyncButton', 'refreshFromApiButton'
        ]
        for attr in buttons:
            if hasattr(self, attr):
                getattr(self, attr).setEnabled(False)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
