# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MrvTerakaDockWidget
                                 A QGIS plugin
 plugin for the mrv team in iTeraka
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-19
        git sha              : $Format:%H$
        copyright            : (C) 2026 by iTeraka
        email                : rosajohar@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal, Qt
from qgis.PyQt.QtWidgets import (
    QHBoxLayout, QVBoxLayout, QLabel, QPushButton, QWidget, QGroupBox, QSpacerItem, QSizePolicy
)
from qgis.PyQt.QtGui import QColor, QIcon

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'mrv_teraka_dockwidget_base.ui'))


class MrvTerakaDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()
    auth_requested = pyqtSignal()
    logout_requested = pyqtSignal()

    def __init__(self, plugin=None, parent=None):
        """Constructor."""
        super(MrvTerakaDockWidget, self).__init__(parent)
        self.plugin = plugin
        self.setupUi(self)
        self.setup_auth_ui()
        self.setup_connections()

    def setup_auth_ui(self):
        """Initialise les composants UI et les info-bulles."""
        # Les widgets sont maintenant définis dans le fichier .ui
        # On mappe les noms d'objets XML aux membres Python attendus
        self.status_label = self.statusLabel
        self.user_label = self.userLabel
        self.logout_button = self.logoutButton

        # Configuration des icônes et info-bulles (ergonomie)
        self.logout_button.setIcon(QIcon(':/plugins/mrv_teraka/login_icon.svg'))
        self.logout_button.setToolTip("Se déconnecter de l'API et effacer le jeton local")

        self.compareButton.setToolTip("Comparer le nombre d'enregistrements entre QGIS et la base de données")
        self.loadDbButton.setToolTip("Charger les données de la table sélectionnée directement dans QGIS")

        self.prepareMerginButton.setToolTip("Exporter les données de l'API pour créer un projet de collecte Mergin")
        self.uploadToMerginButton.setToolTip("Alternative pour l'exportation Mergin")
        self.refreshFromApiButton.setToolTip("Recharger les données depuis l'API PostgREST")
        self.loadFromMerginButton.setToolTip("Charger les données collectées depuis le dossier local Mergin")
        self.refreshFromMerginButton.setToolTip("Mettre à jour les données à partir du stockage Mergin")
        self.openValidationButton.setToolTip("Ouvrir le formulaire de validation pour réviser les données collectées")
        self.syncToBackendButton.setToolTip("Envoyer les modifications validées vers la base de données finale")

    def setup_connections(self):
        """Connecte les signaux aux slots du plugin."""
        if not self.plugin:
            return

        # Connexions garanties par le fichier .ui
        self.compareButton.clicked.connect(self.plugin.compare_project_with_db)
        self.loadDbButton.clicked.connect(self.plugin.load_database_data)
        self.prepareMerginButton.clicked.connect(self.plugin.prepare_mergin_project)

        self.loadFromMerginButton.clicked.connect(self.plugin.load_project_from_mergin)
        self.uploadToMerginButton.clicked.connect(self.plugin.prepare_mergin_project)
        self.refreshFromApiButton.clicked.connect(self.plugin.refresh_data_via_api)
        self.refreshFromMerginButton.clicked.connect(self.plugin.refresh_data_via_mergin)
        self.syncToBackendButton.clicked.connect(self.plugin.sync_validated_data_to_backend)
        self.openValidationButton.clicked.connect(self.plugin.open_validation_form)

        # Bouton de déconnexion
        self.logout_button.clicked.connect(self.on_logout_clicked)

    def on_logout_clicked(self):
        """Gère le clic sur le bouton de déconnexion"""
        self.logout_requested.emit()

    def set_authenticated(self, username=None, api_url=None):
        """Affiche l'état connecté"""
        self.status_label.setText("● Connecté")
        self.status_label.setStyleSheet("color: green; font-weight: bold;")

        if username and api_url:
            self.user_label.setText(f"{username} @ {api_url}")

        self.logout_button.setEnabled(True)

        # Activer les boutons d'action
        self.compareButton.setEnabled(True)
        self.loadDbButton.setEnabled(True)
        self.prepareMerginButton.setEnabled(True)
        for attr in ('loadFromMerginButton', 'uploadToMerginButton', 'refreshFromApiButton', 'refreshFromMerginButton', 'syncToBackendButton'):
            if hasattr(self, attr):
                getattr(self, attr).setEnabled(True)
        if hasattr(self, 'openValidationButton'):
            self.openValidationButton.setEnabled(False)
        if hasattr(self, 'syncToBackendButton'):
            self.syncToBackendButton.setEnabled(False)

    def set_unauthenticated(self):
        """Affiche l'état déconnecté"""
        self.status_label.setText("● Déconnecté")
        self.status_label.setStyleSheet("color: red; font-weight: bold;")
        self.user_label.setText("Pas connecté")
        self.logout_button.setEnabled(False)

        # Désactiver les boutons d'action
        self.compareButton.setEnabled(False)
        self.loadDbButton.setEnabled(False)
        self.prepareMerginButton.setEnabled(False)
        for attr in ('loadFromMerginButton', 'uploadToMerginButton', 'refreshFromApiButton', 'refreshFromMerginButton', 'syncToBackendButton', 'openValidationButton'):
            if hasattr(self, attr):
                getattr(self, attr).setEnabled(False)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
